language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
      - npm

install:
  - python setup.py deps_install

script:
  - python setup.py lint
  - python setup.py test
